server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://localhost:8011/eureka/
lucky-word: Tarun      